# Generated by Django 5.1.6 on 2025-02-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_carros', '0002_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default-image.jpg', upload_to='productos/'),
        ),
    ]
