# Generated by Django 5.1.6 on 2025-02-14 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_carros', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
