# Generated by Django 5.1.6 on 2025-02-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_carros', '0004_compra_fecha_finalizacion_alter_compra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='catalogo_carros.compra'),
        ),
    ]
